place route updates in manifest.routes, not manifest itself
fixes useloaderdata destructuring when adding a loader to a route during HMR

```
TypeError: Cannot destructure property 'blah' of `useLoaderData(...)` as it is null.
```

Co-authored-by: Matt Brophy <matt@brophy.org>