Move `@types/aws-lambda` from devDependencies to dependencies
The `@remix-run/architect` package exports types that depend upon
`@types/aws-lambda`, so it needs to depend (not devDepend) on it.

This will fix the following error that occurs on a freshly
bootstrapped Architect project generated with create-remix:

```
$ npm run typecheck

> typecheck
> tsc

node_modules/@remix-run/architect/dist/server.d.ts:3:135 - error TS2307: Cannot find module 'aws-lambda' or its corresponding type declarations.

3 import type { APIGatewayProxyEventHeaders, APIGatewayProxyEventV2, APIGatewayProxyHandlerV2, APIGatewayProxyStructuredResultV2 } from "aws-lambda";
                                                                                                                                        ~~~~~~~~~~~~
```

See https://stackoverflow.com/a/46011417/167694.

Addresses part of #6296.