Update sort-package-json to 2.4.1
I think that this might fix the following error that you get when
you run `npm run typecheck` on a freshly bootstrapped project
generated using `npx create-remix@latest`:

```
node_modules/@types/glob/index.d.ts:29:42 - error TS2694: Namespace '"/private/tmp/my-remix-app/node_modules/minimatch/dist/cjs/index"' has no exported member 'IOptions'.

29     interface IOptions extends minimatch.IOptions {
                                            ~~~~~~~~

node_modules/@types/glob/index.d.ts:74:30 - error TS2724: '"/private/tmp/my-remix-app/node_modules/minimatch/dist/cjs/index"' has no exported member named 'IMinimatch'. Did you mean 'Minimatch'?

74         minimatch: minimatch.IMinimatch;
                                ~~~~~~~~~~
```

...the reason being that the latest versions of `glob` and `minimatch`
both ship their own TypeScript definitions now, and this removes
the transitiive dependency on `@types/glob`.

But I don't know how to test `create-remix` on a branch.